audio_list = [{'filename': 'eguitar-1e-e4.wav',
                'path':'C:\\Users\\pedrohbf\\Downloads\\TCC-light\\data\\',
                'f0':['E4'],
                'duration': None,
                'offset':None,
                'sample_rate' : 44100,
                'predicted_f0': [],
                'results' : []
                },
                {'filename': 'a110_s5f0.wav',
                'path':'C:\\Users\\pedrohbf\\Downloads\\TCC-light\\data\\',
                'f0':['A2'],
                'duration': None,
                'offset':None,
                'sample_rate' : 44100,
                'predicted_f0': [],
                'results' : []
                },
                {'filename': 'b247_s2f0.wav',
                'path':'C:\\Users\\pedrohbf\\Downloads\\TCC-light\\data\\',
                'f0':['B3'],
                'duration': None,
                'offset':None,
                'sample_rate' : 44100,
                'predicted_f0': [],
                'results' : []
                },
                {'filename': 'song3.wav',
                'path':'C:\\Users\\pedrohbf\\Downloads\\TCC-light\\data\\',
                'f0':['D♯3','E3','D4','C4'],
                'duration': None,
                'offset':None,
                'sample_rate' : 44100,
                'predicted_f0': [],
                'results' : []
                },
                {'filename': 'precisome_encontrar.mp3',
                'path':'C:\\Users\\pedrohbf\\Downloads\\TCC-light\\data\\',
                'f0':['D3','A3','D4','F4','C3','A3','D4','F4','A♯2'],
                'duration': 2,
                'offset':None,
                'sample_rate' : 44100,
                'predicted_f0': [],
                'results' : []
                },
                {'filename': 'valsa_sem_nome.mp3',
                'path':'C:\\Users\\pedrohbf\\Downloads\\TCC-light\\data\\',
                'f0':['D♯3','E3','D4','C4','G♯3', 'A2', 'E3'],
                'duration': 3.5,
                'offset':1.5,
                'sample_rate' : 44100,
                'predicted_f0': [],
                'results' : []
                },
                {'filename': 'E2_song.wav',
                'path':'C:\\Users\\pedrohbf\\Downloads\\TCC-light\\data\\',
                'f0':['E2','F2','F♯2','G2','G♯2','A2','A♯2','B2'],
                'duration': None,
                'offset':None,
                'sample_rate' : 44100,
                'predicted_f0': [],
                'results' : []
                },
                {'filename': 'A2_song.wav',
                'path':'C:\\Users\\pedrohbf\\Downloads\\TCC-light\\data\\',
                'f0':['A2','A♯2','B2','C3','C♯3'],
                'duration': None,
                'offset':None,
                'sample_rate' : 44100,
                'predicted_f0': [],
                'results' : []
                },
                {'filename': 'stairway_to_heaven.wav',
                'path':'C:\\Users\\pedrohbf\\Downloads\\TCC-light\\data\\',
                'f0':['A3','C4','E4','A4','B4','E4','C4','B4'],
                'duration': None,
                'offset':None,
                'sample_rate' : 44100,
                'predicted_f0': [],
                'results' : []
                },
                {'filename': 'song4.wav',
                'path':'C:\\Users\\pedrohbf\\Downloads\\TCC-light\\data\\',
                'f0':['B2','A3','D4','B2','A3','D4','B2','A3','C#4','B2','A3','C♯4'],
                'duration': None,
                'offset':None,
                'sample_rate' : 44100,
                'predicted_f0': [],
                'results' : []
                },
                ]
